image:
  pullPolicy: IfNotPresent

operator:
  replicas: 1

consolePlugin:
  enabled: true

workload:
  enableWorkloadScaling: true

containerizedDataImporter:
  enabled: true
  argoCD:
    enabled: false

network:
  permitSlirpInterface: true

priorityClass:
  enabled: true

# Storage defaults
storage:
  defaultClass: longhorn

# Custom resource definitions
crd:
  create: true

# Service account configuration
serviceAccount:
  create: true

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Security context for containers
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
