---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-api
  namespace: obsidian
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: obsidian
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`obsidian-app.hmdev.nl`) && PathPrefix(`/api`)
    middlewares:
      - name: obsidian-api-stripprefix
        namespace: obsidian
    services:
      - name: obsidian
        port: 27123
  tls:
    certResolver: letsencrypt-prod
    domains:
      - main: obsidian-app.hmdev.nl
