---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian
  namespace: obsidian
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: obsidian
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`<path:obsidian-config#domain>`) && !PathPrefix(`/api`)
    services:
      - name: obsidian
        port: 3001
        scheme: https
  tls:
    certResolver: letsencrypt-prod
    domains:
      - main: <path:obsidian-config#domain>
