ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  host: <path:dev-config#domain>

  tls:
    - hosts:
        - <path:dev-config#domain>
      secretName: tls-dev-ingress

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce

ssh:
  enabled: true
  port: 2222
  password: ""
  authorizedKeys:
    - <path:dev-config#ssh-key1>
    - <path:dev-config#ssh-key2>


service:
  type: LoadBalancer
  port: 22
