---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unbound-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    clusterIp: AgCgVbP19u1/vBeQkWESytyDnHqjDAHVuEm9OUpwgF3AhSUWLpVG7nLf+4XEe2kiM/GeeMKGGiT+rmTvckZxm0jC7qOgfGjb/dFDVXpikLrL+vtyB+98h/0LkVUZbZrunllmcH5MGQH/bQGXFriHRCo0qUKDBsWChQDsKslvfaStvyDpnB6VHY1JxllwUdyUmvR9LpYvDxJYnT322wU+2JdibsZ4MLnxw3rftaNRP3XN9hG3kgwkrVVzoIeetsIoawSf+6OkEURXt7hz+hCTG2ZI02Jjq2tEFJ/pilp72USMhLt9N17fQyfC1D6uo+XIo3NN2OWTDIbQ8/e5fqNrlP6BtNOhifeVigs02fKQHwPGPwNlistduxOG0ociBeir0K5FafnU/vPNa+rNIFFBvO8bnEOPg37LtZWmSeLgJ0m2uxLQAmrLWc1gaPbwCNRTDHZM5ys2+GRFgEp14HTgfy2BRjLJ37RaUKB1nYQL2XpFzJkyyvqoZabTzOEuKp0vn5gUsfeGTt49VIW5nIXVMOA2ho0Am/+Y8nNBhtn6XwBhbarS3IghD603oC5lrWJPK+V1PNli6Ite9xNgTiWPCBYhtQrZGeuYMCZoULNKnXs43Jiawx0V8/sdIz7JaPQ0NfUm6T8NuCMDQyLCFY0JNJJw6Y/M4+uCmXD/JNKXSIbq89MnaDCwF7O3GwYASo8w/Z14nmvgNEObi3hK

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgAwzp1ofNlZc4DzQq4Si1fs/4y2bIrH8aX4aK8PPu6uIb3W7p3p7d3L2u60r/P8RE+wN8vxtoftKcHrI6sqsqBZh0wodwvBJRdQWQT6rGCHr771/vXGqE2OEoXtgz6raRBZoUYwvWAIFfF9bj3mFOIbIIIhu9o74AlVehA8sHmUakCeuu+2xWt2OQK2ej/vR4RQCwk3GUqeeyV0MzvzZ0BszaLKOAcd7/e04t97IRuPfeIs//IL3mChBiANjl2Dr9sXOD+L9FjhsCbKLzmjT3x8g07gx3FHe4rMeHkbnypjydCgg1dFFtnL4+qQ6D23KmGoC2WLvxHirKYzJbArp3OLW2egTJ3nSGA8g9GFKDOpgFdbxGuMEyW+sMlHPwsk9N3KD+0LVxSgMoyRtJaceZB8voq1nLO0B8xjxmj2+wxiziawimypjYto94JGCbP1pcO8evc0uPviZSvyXWd5t/2dkt3B99PG4TgsSOixz+rxgbfOIe8LHoK46i4CXWMu+5UXgFWt2CkYyRk5TO1Ufledoc9V1XKNTn8sL6miaG8918IlgiyR4UbJlwL8fdX6nSW1ttEw9r+74Z2v6V57nBLovgIxWbiMtSql+SJChuxlfxZviYW6MoTa6AH2k2WKA8mrToOsl2n5bAVEHv5O1SnDdWXSI0qx8pED7JvdrbhexuOQTRITr1Hz6WXhSG27jsbyOKYXBiQ6UE1WSMUp28U=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secrets-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgBfcpR5A80IApxARkNxsXRJCNvJCj06qhj5w86pEBk2+PC4ChMubWSn7DRbRlyV6aYEZ8eskMq9dvz8TBVLipi9nPTwRD/PCLfnHQyjCtEsT21U1oDpSZjqKXE5NSUxb+3H+/hDcFqJO2HcX0kJW6O07KadBuQM4g8irYVsBi3x4GdoXVuE+z7gRm20Xt/+kYzARVNF1ckT9VJ0G/RE6GoNu3EHPK6JspBE+jkI9n595cLIyeEiuYFwNsDIL1r3Og3jqBw1Aov6JwtRVcvcymu4K6/6dEpJuia6ne8gsX9LoWitgXhe4EkgApsfkSZIOMC52IHxx/uDhbSXyT+WA0vbPlUw5fQc8yWnX0mTK6WekWA2biHrDkQjqRAzX+PD+YW1SZeTzwWobqlIMEoUrens7CZTKBy+dNxEqL8k+w0xjcjU6kH1wluEl6Ap+ANOhKZ3R1X0kM+bEr6QyuHT5ueRS5D6Gb7eRgJO55GUmOsu9A0bPv8aN0eYiogEF2VPaHxKDbQgZJrCsaKoGV3nCn39pnZTdbmQGfq2zPZaT4T9J/GgD+gEahJksJSS7BfHkVlLXeUZAFde5fN+TKJ47Bap/FKZ9WLYrW448QzL3qYZ6Ma3NOlFxz4ka+i+P2NYZVX2YHy2rPd93xQmE00XEsld3cgJVS8nMKcUyP4KbwwceU2vgBCFhmO5f87Djju6foHOFgmerX5s/G64OC1cfnOCHViTxAk3lw==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgBJIB1qlqabPfSg8GgjNtB+Av1dZsgkCT8YE0GPNmlpv2BravF35w8DE069JUoOZ/+Tjlc+AfBF3umnKidXsAfpLvip5W5GRKxX5MbFC9hfLB0PGtIVZIOIK55v6a+x+qvoun4gn3RAw03DTa0BzT5sIm8sNCItR+kwnVNnmrzuwtkUMGRl4eixJ9okEIlZZZAktuODr9ipO4NogkhMn4/dCavv5ZJ9Gja6fGig0fL0DzPdz2E/LO8vIyiI7jn9WpEn7NHaIHSPbWHl72fP4Gs9mHGvtogrvciebqO8zhHa3+T0XzKMlzO1KAlEAkM8YVjBDm/1r5I9bkhMQClvNe2IlWW4Z/y+PjU1Sml0rPO9esAEhWyurz+2eC7cVEwYyGuKFLBitj0+KhUiGF0iLOo8Q/K0WswweIzHGdPyVTDV1a+jg8xdeAtTHF6PTFJu3gTUkb1SwYy2iuioXOcy4/NrW+N14X4NZb5J3QLCI4oMipTwOf5KlaG9cAj7isVekZdg5hQ6lqGuVRnMTDLV3w0AvYAf6DeV1pmP6KuFsixReSRiM7FM/jTVTkb0uDuJ/FN3xvWL2ZZSxYO9dwRh/EszacBuJqe5KlUSivqHboUzy3Qc5DewmxBeG7qDzCdemtcaA6Nn1V32lBbeqJ+Xbzc+I31e3DjTSXhu7IRqSOUygJzylXXRglX7CW9JWuW8++zVJFy1XXsyejP+Bed2M/swxJx82A==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCTZqnUSLBPljqYtsKsVJochNOjkJxpKiWW+Rb06RhkuQjn+ZHFzwh9Bm25PFQTdpO7MNtaulzLoeCg+w/W5EP2JlMCRl5qzVbmOuEC7X3ojnlB/KNsmhlm6icmvB9CGhmjxDxA3USyiCEAHktTn3cfun/czVCxxFxhBP8xcdoIcqjAAoltKxDDO0H1Q8vp+iWodsi0ppLj3pxzpbP18f7C1DLStsMqCYCV15+Gl6YofhWbRdZ2RISHaYzjLdybO+dA0xEoixOzScu4j7W6MqVdcJwa+6f9bSSiZMF90S7vfX1TYNxOSu2BPcg03v9WZqKLy69TjqkkeFv1a0b7Fip2TfHLJOFkkTw2pGJmXcRm5tU9wovOoCr/7kdl1xZx6jA3j5ad05MzxNm+IwXEb/k2gQ1VLw8/NtrtS144iMYfbivrMWUcgliovb56ojPPxJaKEyRNnun82RXNMHwKcaDGs36bfEwrodu9tBpRf0/JaR8qYKQr7XHsNNcW3HvmuEEPElRU8BrwF6jHAprTtOQgCkGj55NtM6mJoUdciJyDZPAZT3m6+imoSLGAAe8CuzhkpsUxm/s4Pv3ww2Jpfk5/G/73ZNe63edFGWdDEjGXRY8LP1yKKJrZPDaaqW8WYlAXIxOElzfVab4A13HMy8FWpSBivgm1932LTtGpTxYytp3JTSSkVpmnAewCxrEE06cFIVSq4PJ4gYStHw==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: esphome-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgDVh0qHYlJsEQaoxpFs2lbm46lMr2q67TS83ojC5+4+bfAdhwi4b76ke6Y4xXtHqfeqdeIw9C8VTrsd5aJxlh6461mf2ZUKrJaQ0lWNM+r4IOiWB2y4p8VpxMvJeOFlnPZh0olAyWw2U5vqo9FlOsKC/gd69nUocca5o/Af+if8Jf6q5WXLiobY7OTd5GqjUd4r983/KSOTlemwKzwAcGZwikWVE74p48o9DIU+yQVLdMBh56hXIkJRwRCuW65XUDxwpeSB3f4SuOYQePwbRSa2velc/96PViTajvElpNtGqst48aIJa07BxtIwLFhqGg40K3wqCSLzfrhu+sPjwSHKV/uI7xp8NC3dbVnnxSlCZy44EqbLiwe3lVA2fb1cAYUbgzgSwOjPc2x3/DP+m0h/OmE5EzEfZzGYaKrC5M9GVdNZGCZxy0MfMLWtvfSZilm65BGrvUPnMErOyixscXPct/NKsMJ5gRJAfLQkn8usuWjk/PHTMZov4TRkDWvMiqGPdRE8RWE0w74KztTEtCiK10HeGzBWCcuvbAwN2Y7PFDzfaqpO5KEqsfeSLUyUZhEHrBiQnJ4uIT69nMrOunNJNMlDsAWjUHnLkCXTtRNI9Uvu0W7qxOueKbX9hIFaIV8HTiiCriLskktewcPjx872P+kueH3Tc2zNwGlmeizR8vsqA/y/Q0hA+HNBL4eGWdXTam8Dbqoahov1hOpEPEFJ

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nas-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgDTSdQaO+aY4mTmg5zDzAsCQsR+Uq93ms/1s+K8k3LNJG0FPYZRwRSmQroTPiUBDqMkn5r+8WOeEr9JaEiEARmvl3hvjSbUQqQamUIfgJO7qt6HYbobsv9fOlvvdn7xt1Eu4QQkQ6AeLMXVMOrzIoDjM8ym1gwUyMGuh542Z3zMgBNqhVWHl8gY9lKil2YCHS9rVMDEpymzuIUuMs69WD+yx/fDZ6aa5y7ZobTFlBIxlm4xIWevKKocT0RTdKF2nr3tv2nCSxUdcDXHEmC4ie67+sFvjky1EPYgwn1i+EoZjWSrDeiG3owMulYq1lVC5614UvAQJc/FP3O/DQsbEerhBtOXNZ77GyPe4S8YhwqJFdxy4ZCMSI6XctiWL+zVdnrRx08fOWTXk6YSJTrl3sCjAX8AdE+9ZCgkFH9zcdc+DEFefiZ6JYGKdGGk4EMSIHHWX8Lg1UYTq5Ps0unLnuV9dpru67AP5iTtMoUPhQYCQ9+cl8KerTUwHiHyiY8lzoYh8MNMA16jIpH/1pFye57e62pht9xYcbAewQjauEGgjc/pTYyuDckj9vTS09uREzD2D8zMx4miIZuGsUxaefUpT2LFUfcQzt5XZd8K0yzD+Nriz2DfYAT5o0wFc8XbncPBjMXosOV129z43sO960YqYibau23TmLr9lTigVg8FBk1nIryZqYcK+s/jp+U1DDXGed4zOCV3EY+CZZo=
    ip: AgDTbob/bp61ct9dkbUAjQ17WSbo0FpaBiHxnRevTjQAdmArKRjeRdZE7FoQXuC1gN/sXowm3AOj0+/MjyT9qqaibIrcOa9YpYnikBtWYADShBXe46A0iOtgBz29WtbFSb1f0LX+9zv051VrnpXBL9fK8qn2tTdgZf6BGqA948tGUDHMqWCcnQkMc/CtKhHx8ZfILgDsCY8M1ORmJR5kdG2+8thtKxB/cTa9F/YPthqch0VdyUJkzZw65DqtnsO6pdWX/9/7aqXhe6Z1fM0V951PlEswvVeW1kbYf6IaLYjcL89ZO9IrduRt0bonRvs5V3GVSRym0Fz0EQzFcUx2bcOLrxWqjIiwiprjWTPpFXr1AXFUR6FLIXvPI2//ShXOywDR15aGXbGexl1EfRpJmck5pfZco3bTCql20gt2u3g+H9abmdgJs4MuKXBAASpgAOXSLkRYZ7O9xzAxrLIPuJcw1roLF9wDdUa+AodNgziLvOBO/wnF6lWIT/vr9aBluRuTMx+NFthvxS0cZdstJIaniMzGcHeQ+mwIhN3ZBbMio2qzDPbVbboEF0u1DY7Pz8SPg8RTj1nEoq0dR0+HtqIA6tJRRtdlDfdnLC8i02K47REk/kD7Bfc4lft51s9HL9bl+H2zTBYr7plOrrOFv3NmXx6tsZQcEkfgpIaln8P+lW1Zx13aK/iBkhJ/CMyguCdCbbWk8yX3Z9olFjQPl90=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCeAaqB0W1XLTNBpXHCP+2EZmNN2XMgKGuAx6dmuR60d6Oh5sxv8xkX4+fgtO4QrAX716lWxCoTlUVcZLi1pPLtnnB+hrWbuoti+SlzhcWchVaBWvrncLKBknamlejJoGjFi5aw552JxEbJlfhKWfQJtK+Xtt37gTuDnCHzgLb5u+TxNMPxI1KcmpM6CDsscd6dzDyPTDkjnOaTbxp6MYqXMb8cp6Cp25fX0E270HXyXOC9fN+A1AYUjlhzQ86K5eN925NEIvRkHaHhTZn6d21fwFm7QbNVdbUDwBIVUFrdb0E3EZ/2uV/t3MA/xUcPqdT7UXj0aeNS+ZOuVuIAJODQUB6A+ia/yaCIZiNybYgpEt4ojaUlcoG15cf0rntWGw3dv+Hxlk2oF2cvytBBcXDlmCB1+qR7FL0rddmvHFIKpcDujKfo5LU+PcQLrVsomcLNccTCWaW0t8c9DUIU1UUUnQxlFsz4BeUq4nPdCr1Kexo8/IBvp6rf4ax8lErKXbZAjuR+xwuDth5brKKRZxWYbxTd1tmSvO8QBWAIyJvHiBU9++O+KZUWUyjR2g3cy3cGA//5kH/9JavS+cYo7zwpyQhgZCRxjDi03YXYUqL2IDy/vIQfpxLuw6IHGdCGEeoh9dqHGyR48SbMclbBZwvDD214sKV70zrIKh+CiAgG84KUdtsqAJi9tD0Nywpd2VxWuOdj76mrO5k/74H3Mg==
    ip: AgAfb+K/3nvg/Fqr4mWHQ6i9nBKdp3m/hMyfL8QSp8x2Z1XHks6iNzCOdRvSVWH5jj17tqg9Fvp3kEsV5nb2huXB3k8wwEpqIkdKj9cKjm0QKU08UmB5sYstzBoxGId/Jm6Q1aUIQ9hNx7ds5L5krnbIirwKjsMedUD8kh7wZecCurnJYrArcAJnfPF2l+stzc6VB6GZWfuI2FVHN0+6WTPOJ2unzRcWDMP9hsbEv/iVlWUdTjFkpNMleo7fLo2gUA4pfF3zjupWbJxXE5rbYfHKMjpNNa+GB6qmkbuhbNJOsYqNP59dBC6wZZEitucj9fFDVEWnoyGVysgMc+NXIRGM/tcXYbF6VZ8Kfie+qJTM3UUPQVInALrT/ROb7jK4WOjHDRQwALuW4fOhUru8qbvmtubR8EmbTwbP9QehV+V3LUleWCmFwAg9H89geQb2dxyVPX0AdZYCZn7jqufHVklmaEPWHO3MiNvwHNHngOzSIBKS3JU+zbWeYeszkYYxV0jSFNq1xBWmHc9PUVvF1oBdy5nlGcy+MKs5LzjV8WA+N2UxYiKFRpSbjxgMRgaHdh6Tq4ocZxzy3UwU/QH0iFw2AyAMVqT2O1KLU/YZOz3s+mkZ7WNC8Go8VTSb8nNq8PnakmSEQ5kkVpDdyrDwlLXEnGbMfRAs7wF9fY5VhSfh6p+r30ef/nxMbiYPjODoSYjuak4EHgEU+QoO2Ju2

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCsu2TffrShg+45lHzIGBmeomCg0OZAfMw7IjFnd0LlZiPWJDbeZA7AV5XIVG226vupTTlr+hsjlzkPHclCW00Sf3MZA1eajT21wr3/chcfmfRH1EeZhdIkKzWhzMtK6IWWvn+4XtMLvk4vnLIHIr0e4NNdT/W6JqGIuOp1onjVDc5Fy1sL0DmEm2uj33xedgvvs7msYUsWEBztAUcqeWo6iEMg2g7y8Wb35Rs0M7vstypYrBfa+XLuAuM+w19DjCMI6kqjgLQOCwga1MjkYj2FCy+K8iIpOMeBtQ8Jkc35wr9mr2wCLLClcQHsuC3YZkDKRXGpNkdYWsE/sJ2518to7YSxufqj3sssd4kVwQ+Fel6FnFAyKFjZoNRf+bXj7r9eLOP7AI0dJY4SM3Qs2aTY3ZVAj0BhlQ8wHT/i40NGGXcfw4ZZ2ZSsVpqLKMHOb0uP5AsPoShHlx+166OU6OPnvrEpZc7J9WNx227x+Neu78DD4SZQItLuSLQDjaELZsoyMXqgAf2XFbdiipTosE6o7jGqtQz6Gu8HlQupHU2JLg/gf5Hq9ZV3gfzUf81IFl29G6VH/nb9B1shZksXOXlZdDwzHMS4raj0iDSVkhYhwDKrS4nk5IG9NBYJ1/9KNg/CjHJULyBMVQqoKjTmx54h9ZbyACWp9oAgB/+tIwyPCoanefdlqqW3I3HZVuth+GcQHCbv8hh7IKCkgNiddz0=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCPo5rFwP3i1BU9Cr/eCZ/N91LnmVwg74wWp5LY9Kjyd9Osev7TvGJbATDM5ZVBvFL1mwJvexe3QVWxIQRf+UkJ4gP1Iab/u9jMnK160zU41Nnj2fSUmV+IV6Pt4sjKFEuiiM10QypBvBNuJ0sqPmHqOkTDSXCA1RMNpz+JpIgNWhL3zzFEztuwi3VjtnD8LbXIA4yzAedvS/rlXqo9uST1NT4RD6VClUSE+cxRZy8HzeSjAWX9h1o8KyUc2tfLNF5qczRlCWTLMzhYMSqRYRxo8RmdsCvHeeXQR5IjA/vb/fmyDvk3QkuQABgRdmwMUSgPIoDdBWHkKj+AGPPFse7Rd8xZXsREx6NEzh7Np+sj5aGAzEHlm+tT9cwkaG1JO9MhvdZXryLX+Car9S5xtbsgddXBSPnT8I6D1+SkN5v7XLXDZH+ZBWqbhOhptG/0ltfPjAUPPsdNhiuVWTTdeS8SARSoNfEcBNXqCo/X/KvPhgbAKVYVEAgIQ99dA0UK0KSTd5Qe8/UIs9kVyXI9YxYRmP6nrYKWsZ9aMQyYqlf242ShJkJuh869tf7Td18CRVql/IhZGxR9HYGp0H3DHWiSB/f5y2+uP3paaVicZTPRwiJua6I7a6iS6r6nnNNCiKq0UpsWeYrOicla4eWbi2IXsYiG7tDSrClBjTOdPQcd/1tSLCmV8YGo3mOVpedp9gyu8zF+Vm7uNfdaO7vhO78kmA==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgAudu0km7xHHmutC49hb0skFR6fMrwgJjWMMb6qchpC1IT4pBYDBgfttViOj6t47RDrMFl4eHYgivQ67IHrVhSPDIRmSi6wYNtBheCPcU11VHFYeG1JneiMHg16nEVbv3DujYLyK1cPJDX9s7U14MR5AoDgbDII1tSDcB6Yjit+29hDyjCReuvRCeBWpWFqQWvulErpN3tS25sC0cpiaCmHq0tWiR9YROI/XLD+HHoxhD6JEPgCzi8sRVtVNYNdSnPC7EA2J+AGhlGPxhHcnK4AOB49V1V5Q8GGPW4TVA3qVjusDhuR4uyTxCITdNNYon9BSOrmdJf0j8TWiKALoNGEFOaYuIFMDukrjIZooQdUsFcNHAveSZ8xbqSfqFIrN49M8TTYHWTYI4yT4Oq9wE15VUksDyRT9Dba9BQK1yrzfiA95V3BsC+BHD6Bngdoh0gWjABzXYFW09Q5cVyMAurF4iLCXQD8mDBkZ41RL8ow/f/oJ99xS5xsN9uGU/o9STpEcpdZDrJynhGrjqN+DeFdmWn0PV+y25ijXR5oQwtCJzRg39EnNljjMO1UvifGLHJ25CZ1dkohpRcfRYMiAeprrs8JLCsC5bw+GKhUglyyfBrc1PjIJDAVNLH70zn7wbnOcp/HsrKmFryipwzE8yJZTq6jGbVmXUl6WA8cG53/5gLSZA0BHONGNxV46F36ikulsf0Nr4U22JviilrZF+y9nw==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCyuHiG2k3SdFkY/5EnDga9bOa1JhCaQ/ADjSj7MhRyRGCARt+2v6HiSaYhnbanUzMO5PDOn3iHLmihMuE/ROeM9x0h6giMKrXRAA4qWPj9XaM9PUNRPDzn4SKPmkuIHEU+XOtJhEaNvN6EIGQLSZE4IN6tV7HjUz1Qdjg8+/lIK4B2lvbgyn0kgv3SppzjlQ3lkKsGXGRUSymGO/dCYSgE3GJFAz0lssZvaa+PrtHLPo5bsUeegvcyCAWCXTDAeanXJcK/caNQ6s0N2WRiUF7ZHwPB3HUkgFQJFD3JQmkATQdI32tk5ZTeN+njxC7bU/tI2rojrCa4frFWO2Jzf11+I3fICNPnITQK1vYpVVAWq6fTphksMDwjDaAFnXsT4YioHY5+2vqIfAstv0pwgcjgEZzgSSqUC/cKaasCl0pv/Lh5NI5qCI9e4R3F0ftLGYCeCvdxab19qwvv1WPTJ3xGDdpy6hQmwlRi53SUUxy9McYeYqIi01No9ev2MBpRSWhkSIAlenwMVz1qXA4HRfpqZ3zxw+1+qY0XCDpwamOK2JcQBuq0kllpDqhcQKqbUcC3gh/srMVfJWJyVxz+O6bHm2TM/NjZKZmRzlABleJareclKbYYipmQkrEdHNaGVpkkm+1jkt62Hvsx/rHOr9uCCtUHdWX26r5qg54t3s4oDPlBkMx21SCcQlyo73kYUrJLxFn3vlETvPEozcd8U+I=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lidarr-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgAgRvmJzYe5cHdLg6vaNwas18jJqM5jQ3ZG6qY4wraPI8vMk9X+nN4FMj/HHzdWOx44yWdJcaF0RuTXAGX/IbkhK2CYIF58ZN5L1UQyaSMXxJZirP8l9ZElg4qr20vuJ3YMrnG57HxIB7gm8j+GzqGsGmVNh6z6P7P2fXdBh/+SsxURf9iYg/lKkLULTSyi7grEne6S/DVvqvUh8B4xQjFexc9wTDCFBQQn5HPbXBXwAOepF7FhxrQggpijWtY2IqR9XYP/Lz58s60/QbZw4KGhlcZd55P5cc6UvWct6E2bV1S7YyLOn1GF9lpKSKn1VCt4hGqE5XznZ6COnDBCoWK+PURRUTpDj20hBVJbqra/0k7XruarbwwHTbylcPRz1r1Ydpu39GWva9h96o4LenzzrpeddKkcsoKLNqIqdKefETo5WYeY3uHSNB4N7ikBHr841v16d17I52jvixB5vV5X2ukIgjKiPWDgmvTq4OQ7CzFrPfi2FIPnCr68HL27t7Y/e/JX6CyOuC1vNMb03TlQBmrpGYMNVv2N0KOeXI6xn/a/TVDcQtkD7e/bXcfr0BdBtOUL3mfYh1/cMiXZSPvuWXo64iIA3VyQEmqgxK6Bb8hWIGJHNnCo8zaCviMIdmU4kA4PjAiX8PiK5qUO+q/Zt1KpC5S9L8BzkTNnAW3GzCWZRcXGjyIrh7CB2+BMgeSYT/cjiu3l0k7D6XiBxXE=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: readarr-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgCb8Ryp5+cRwrX5ZuWcEcZZrg5jSOMNUC639ghYGLIi7lAglUj01wf95mzgfVVKCM4NVBJ4Db1Klif+cGbK+0r8eXKddxgHGGzJVPqG2qpkuisZ3KhtIDD8dXPkqDUifbYmr4kJY4ASHxpkqqioZfsBAJ8YNu+FXkY8RZyIO3gKPxQ1vk27XC6bmJBk/yd2smrgC5icVIa+kmet8kY0/iBZQpHKCI5Mzk2emZqNVxjxOlYVBdqvgzwWbnfzZyBOSUOQL3RoziC66Dz9uVHvYDY4lj8A53njBTHLrD3nVVrFH/ix0e3Tt3HQyyUqI+Ai/kOgwEsW61VXppDkNiw4HgjPsLKyTGMxZS8rLMNvjo9X4FjXucmafRJgY8LzAjWbtNXTa54wAzT0VV+fOrfDnW0K7KZjb7xFmsZL5XLXPglc5hDVOzAskYx5HHgzsA8Nr/mqZ3CMHOHAEoOpvvy63HstaHVe6A5+QV10p4V9jmLdix1YUeA0YjVZGJuvKWcm8dMqtZvKwKpZe6MQ5QiXcWkYQvX7GZcBOxqpVgttDTQ9QcV/6c3+iSH4k/Mxx0xnACXHC3ZVofxxy/9dp1khkA3H7+HZAc/j7lwpBRhwM3UEjV9FS6fXsIHZRNSyEvfJaZsrEF+Q5xwUQw2JyV05U/AIz+0aHGd5bjgYYZgdh/kvZy5r/0ljeflkrrDF1PjFbvp5135eDRF8u5J9UMssLFCH

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyseer-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgANRUAvrEpEUIenLxxHF25+/kBTGdTutkuVp5g2wmdWnt4zNW0CmDX2+Bigi89bZtcn0fg/aecqQHdhGDt3T6jybn33ZXDjzikYoSZHJWyWi9iS6ogc5DHkrU3h2Sc4ENuTejmRy/3I/s4ms0d6Rlt5Dp5lP+cS+ZFNX5jQqtyGEni8lBe19q2TATnh5afROVanWyx1LrXf0z10zmuCN6zPqIOuLS7bDbpnVkUu+0AACtVbeH9oQ1URgpGLZYhNQWmK2TE8LAMHqxE4Tf2RS/PjxUO2Ex0A5fqW4NbBTpzOlqvq7Ia81ZxDWyGXgzMC4ofTlP+PafbIIUo5E0wwDTPt/SfJsoyK61LDfLfsE2Au9d50VoZoaLp/3bkDhP79ZpO42McAhktPPmVidQKWg5N8yRGJtrAX1K23vm+xF8Vt9IymeLnEiP6aCLb+RUHElqAkruSl5a+PXtPq1qFXTvWg5BJ0usa8OelGMH9LzH3LZDuLZyY0to1tn56+A/JTLHkkmu/mUzmrv4enDSYyrFdErF+hYiBj+CJOq+YodPZPOoWvgHwJhOJ4oJ2js7KHsmQLXKMrYpz5HtPcglSjmslDfNHWst8spmi+upOf2R1c5jcpeL4BtL5wkyeNjr7fR+PUDohqstC4WgDlu7qs5dMKhihh5uxsvOHPHk5PqViPCZ28kQ8nHFZ/yrg1PXpaZV1GIczi1+cuJeiWOmxERLNA0N0=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgB20dZCcvyXNOb9uUq4oK0KYzympG0Aes7VuEVwrU3jebJcAlXLcbwXZwa2CQ/uXS61sIGT4I3pWVQVNF6drQKkLQSN+VtMm5/78QOPCc4Jaip0ZC8qYLRATb01aBXrumGHCF6lCq6GylAlTSqcdW33U5BXkQWIQ/SfeqwaALPu1pfz16z3pGrvfCCqIqn5vZGH7LrsNRIOotaQXkUTgmju1RBBHDzW6HF8v/91jsJpKjcGgzYC9XFA80om/3rNLvbfWoSfktFl/radEn+ZUKxx/BuJO0XYprnX9L6UMRijI3L9dJy7MrfEin0zNjuNqhoA0mQhy72dKSetCVn+ddrhFa5wqkDsQodKWjxD2IC6AI96eO9Zx8BcEcIooJUF5quoM5d5ZZ7EAPnZpoVHGMxcTzW1ckXMEyBqBAY0bt2l2djiGhgH0Op9wEBdlookry2ghYua94nGnbtDQwifVwnjVFPl+4+jkvJd9yBBYrbCPFm7EfFpU4yjyeY5rfYNYrC9ugZtcY1s/i6paJqzswK7deXzsB7FA1tI5Otuux+TOdUDa4VftYRKndvM2NFVshKzdhZa+LIOnCKfmPDQZNVA3YC1SKIALDawEECXrXDWuYXG3NcCO2wL0A4d3kKavXZhIi6cBefkxFhty2dx57uoNwF3NQvCebQ4GH84PcgA0zyHY33cavHZqFXxaqINAbtVrQ7Tq0uQU5TEcEk=

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-config
  namespace: argocd
  labels:
    reloader: enabled
spec:
  encryptedData:
    domain: AgAE+v4AZcquwoS9MPuf8lsR7iJx+gQShey4KKfyaFfnwgGUtXoLSBR3AAzL+yNH6jTyt/oF9vcVuzrrDKOxak7rPL3i+WJqhNdZYmaCP2Yns9f3C+9xelMXFSuHA9GAst65BhLSfYNV6hZhq7xv5nEMDy+s6L66SD661F3dG2AG+hKKdS7rA9JVosVnnFNnUxYoiuIrCG1XNt9Wa3EyE9lu60gecwvip3+NuhLluzZolliv15HHa8kdK2zY4ME67VkyPCGP2wASU8/B8CP7HYZNoQ7ZUDaFaSdhxvYE94VjdMcdZQSrCdjuV7u0JdhwzVvYYtMXcU8U58XB6tMpolDRukMxifwZn7FEJALk305jo3qYM1uTRSxK+qXzOAF7qsZiDvQ9FShkurUirODxHdcB+O2FR0IsX/Zb5Y8HHeE/8en/jofT+zfzovkRavomkT9c3ZDsoEGYjBJDXSzJEZ5LR+vMuOgg1RsV8iQxufHfR+FS1+m8BCA/FX0kk645JazPdgbHoEMeLcyPniwxuZH1jV78YDoQexGgAIDTJHsw0H62wPMEWwHyXLQLP5YO1O6b9JX715BuqzIZLfBzz9gXfgAKAANbeeYpnmQmvjxBoMswY3vOULzIBQ/BFYLI91sQK/SBEsZF+dOjHga0W4SJjND47GOYT10jRDIDhiPgdPK+t2XLAet/V/mF8usaatjT2ZdylOb5kabfea0=
    ssh-key1: AgAa7izrRuTXIqj6gGykQB8SQlwY+Oy7xOKfvc5KgD5x5kKODx/6k12kbabXowRJJEFNo9fv+THfPqNVBGFphhwSkToqcrd8K/M2KmJ47tHom2LR0wGZ28W1AeH5l5iVPnAsgqknEWWLl4b9lqv8LYU+morVeutOyGKDdzboQFx8VIwxE/W7aobTd23LogzmYpcZgDJQA36jrpOen+cmrWK5n9/qO9dWD0Ccyc0qrU5Z84bk9DknH9jxDVJlujRmDpzDcVRdeP4ki0NlGuqqFEOKQmc5VR80q+Ybm9Qj3upXaWKXAE0598BDMZ9ib4H3x158Aumt4niJKv971RuHNibGwSSsQlE936exOf+2P7BB9d4xbow0XNTFJep/2VTdvO6cv+cpEHcWmIsrbxM9MxlX41EeMNJL+Cqu15qIINM39jUqcgJqHV9N0fcI3C0NgnMvXamGruoCSdqmMeGqfsl//gftIfg5heGtxHplH36+KXRmN+a6//bKcFmNmFcHLRANui3jObRpC6OhFp1bY4hdv84eutTL1PJPkLVSDqeRkzESP1vyshhjPOHc4e3XmGhRFryKMXbph826mPej8oL1ke0yKY3Tw0EAJhUWSqTWl5myNG0vTjVE8nEhl5MkyyyIbsuvtjESKcVPCl3BDpAa2v+LxoiV1yEBQ8jINgMAAFpE0ifqZVe71nQguWZ0rlUPrcCN1qUjn3TCG3GfIDadxEuMQpeupsx/qk8IKV0h0vl+gnwn12dcLEBFtI8YZD54pMkvn5jrRmv+DIZYbaAKmMwNcpFDd8BXX02JoS0VhHrGA+w=
    ssh-key2: AgBAS9M+KPC1Q9Grv6nkVavixFGAXf00ssrGk3ISQXF94LvqNHUviJs1AhQteET3mG4TRPlw6TY95kMa7ZqQjao+G8wLgHfS+6xT5blgek1YRSfJx2cnoKc9YA9HxhI92R0WY8bH6y7L5fZMYLR2eMyRqrvVjYg7vCrlDPpQrtaudYPwJToDCeY9cx8Sv3XWlrhjgBBuo9svaM1D8vqG9QGXbUJ9MlYuZCBU6kL4CWehUkcVeRAui+V0298qkiR8bxPKx0/hdsvdchBB5oByT+6xzU77eYJ3qf+0FZnmLIln7AyMmoO8N2De+wy1yosqYI6IcJJ3ivtPQDxgeEyd+7yxlk/tni2xcVtnxRF9GXkyoYhF6iofexkeJus63lrmrHKj18jzfuuJmmffXLJCE7NaaP+18kowmF8OnJYgfaw2q2g2Gd4J9SoCvaMEI/8g1DDkAdf4RHoVEJtxsqaO/ELgt/3Vza+Lz+bfB457+Hwd2Yp3brO5m0RvpSdvWcEKgTXrZqELHwKu/TP3pq4Edoo0TRBU3dQGIE/pdjuP2yIdFgb4L5TS1YRrx4ZYrlPvn/FJVv0rtrjjiJbRiGvI8Fu6Az1yQjt7W3NYh9w9rZTuyn7dZ7TOgCAT0P7KijXqV/IvSbKog9KIcGZERCUxVdNPxeX79XkdtEyDEGTJz4qNV1EGFdspIH0y8m2tV5beEVDFGiN0bbWgtqj5dhrm3aQ/qJu0V9y8OHQ5OpU2N3tK6d3Yu8G4NwdIiTJwpfXx7uQI96LBWlA4s/+x8gsBDyjS0wdjCwAHJfqkWIZcZx3Uq0hblGigPCUfVVoGGOKVXQ==
