common:
  ingress:
    enabled: true
    hostName: <path:baikal-config#domain>
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls:
      enabled: true
      secretName: tls-baikal-ingress

  persistence:
    enabled: true
    volumes:
      - name: "data"
        storageClassName: "longhorn"
        size: "5Gi"
        pvcClaim: ""
        containerMount: "/var/www/baikal/Specific"
      - name: "config"
        storageClassName: "longhorn"
        size: "1Gi"
        pvcClaim: ""
        containerMount: "/var/www/baikal/config"

  variables:
    nonSecret:
      APPLY_HOME_ASSISTANT_FIX: "true"
